openapi: 3.0.1
info:
  title: VSPO Common API
  description: This is the API documentation for VSPO Common services.
  contact: {}
  version: "1.0"
servers:
- url: /api
paths:
  /channels:
    get:
      tags:
        - Channels
      summary: Get Channels
      description: Retrieves all channels based on provided IDs.
      parameters:
      - name: ids
        in: query
        description: Comma-separated list of channel IDs
        style: form
        explode: false
        schema:
          type: string
        example: abc,cde
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannelsResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
    put:
      tags:
        - Channels
      summary: Update Channels from Youtube
      description: Updates channels by fetching from Youtube using provided Channel IDs.
      requestBody:
        description: Array of Channel IDs
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: string
                  description: Array of YouTube channel IDs.
              example:
                ids: ["UCiMG6VdScBabPhJ1ZtaVmbw", "UC0g1AE0DOjBYnLhkgoRWN1w"]
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannelsResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      x-codegen-request-body-name: channelIds
    post:
      tags:
        - Channels
      summary: Create Channels from Youtube
      description: Creates channels by fetching from Youtube using provided Channel IDs.
      requestBody:
        description: Array of Channel IDs
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: string
                  description: Array of YouTube channel IDs.
              example:
                ids: ["UCiMG6VdScBabPhJ1ZtaVmbw", "UC0g1AE0DOjBYnLhkgoRWN1w"]
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannelsResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      x-codegen-request-body-name: channelIds
  /channels/{channel_id}/videos:
    get:
      tags:
        - Videos
      summary: Get all videos for a specific channel
      description: Retrieve all videos related to a specific channel
      parameters:
      - name: channel_id
        in: path
        required: true
        description: Unique identifier of the channel
        schema:
          type: string
      - name: ids
        in: query
        description: Comma-separated list of videos IDs
        schema:
          type: string
        example: abc,cde
      - name: start_date
        in: query
        description: Start Date
        required: true
        schema:
          type: string
      - name: end_date
        in: query
        description: End Date
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideosResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
    put:
      tags:
        - Videos
      summary: Update videos for a specific channel
      description: Update videos related to a specific channel based on provided cronType
      parameters:
      - name: channel_id
        in: path
        required: true
        description: Unique identifier of the channel
        schema:
          type: string
      requestBody:
        description: Type of the cron
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: string
                  description: Array of YouTube Video IDs.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideosResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
    post:
      tags:
        - Videos
      summary: Create videos for a specific channel
      description: Update videos related to a specific channel based on provided cronType
      parameters:
      - name: channel_id
        in: path
        required: true
        description: Unique identifier of the channel
        schema:
          type: string
      requestBody:
        description: Type of the cron
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: string
                  description: Array of YouTube Video IDs.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideosResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas:
    VideosResponse:
      type: object
      properties:
        videos:
          type: array
          items:
            $ref: '#/components/schemas/VideoResponse'
    ChannelsResponse:
      type: object
      properties:
        channels:
          type: array
          items:
            $ref: '#/components/schemas/ChannelResponse'
    ChannelResponse:
      type: object
      properties:
        id:
          type: string
          example: UCiMG6VdScBabPhJ1ZtaVmbw
        snippet:
          $ref: '#/components/schemas/ChannelSnippetResponse'
        statistics:
          $ref: '#/components/schemas/ChannelStatisticsResponse'
    ChannelSnippetResponse:
      type: object
      properties:
        customUrl:
          type: string
          example: '@nazunakaga'
        description:
          type: string
          example: ぶいすぽ所属　最年少！５歳可愛い担当花芽なずなです♡ 好きなゲームはFPS全般！
        publishedAt:
          type: string
          example: 2018-09-20T11:41:24Z
        thumbnails:
          $ref: '#/components/schemas/ThumbnailsResponse'
        title:
          type: string
          example: 花芽なずな / Nazuna Kaga
    ChannelStatisticsResponse:
      type: object
      properties:
        hiddenSubscriberCount:
          type: boolean
          example: false
        subscriberCount:
          type: string
          example: "357000"
        videoCount:
          type: string
          example: "1183"
        viewCount:
          type: string
          example: "59373115"
    ThumbnailResponse:
      type: object
      properties:
        height:
          type: integer
          example: 90
        url:
          type: string
          example: https://i.ytimg.com/vi/Qh6aSTTkmEs/default.jpg
        width:
          type: integer
          example: 120
    ThumbnailsResponse:
      type: object
      properties:
        default:
          $ref: '#/components/schemas/ThumbnailResponse'
        high:
          $ref: '#/components/schemas/ThumbnailResponse'
        maxres:
          $ref: '#/components/schemas/ThumbnailResponse'
        medium:
          $ref: '#/components/schemas/ThumbnailResponse'
        standard:
          $ref: '#/components/schemas/ThumbnailResponse'
    VideoResponse:
      type: object
      properties:
        channelId:
          type: string
          example: UCiMG6VdScBabPhJ1ZtaVmbw
        channelTitle:
          type: string
          example: 花芽なずな / Nazuna Kaga
        description:
          type: string
          example: ""
        id:
          type: string
          example: Qh6aSTTkmEs
        publishedAt:
          type: string
          example: 2020-12-31T12:34:56+09:00
        tags:
          type: array
          items:
            type: string
        thumbnails:
          $ref: '#/components/schemas/ThumbnailsResponse'
        title:
          type: string
          example: 【ぶいすぽっ！】Blessing ~12人で歌ってみた~
    ViewsResponse:
      type: object
      properties:
        daily:
          type: string
          example: "1000"
        monthly:
          type: string
          example: "100000"
        total:
          type: string
          example: "1000000"
        weekly:
          type: string
          example: "10000"

security:
  - ApiKeyAuth: []

tags:
  - name: Channels
    description: Operations related to channels
  - name: Videos
    description: Operations related to videos

x-original-swagger-version: "2.0"
