name: "\U0001F680 Feature Request"
description: Have a suggestion for how to improve spodule? Let us know!
title: "\U0001F680 Feature Request:"
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request Form
        Thank you for taking the time to file a feature request!

  - type: textarea
    attributes:
      label: Describe the solution
      description: A clear description of what you want to happen. Add any considered drawbacks.
    validations:
      required: true
