version: '3.8'

services:
  postgres:
    container_name: vspo-common-db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vspo
    ports:
      - "5432:5432"
